// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message_group.sql

package db

import (
	"context"
)

const createMessageGroup = `-- name: CreateMessageGroup :one
INSERT INTO message_group (group_name)
VALUES ($1)
RETURNING group_id, group_name
`

func (q *Queries) CreateMessageGroup(ctx context.Context, groupName string) (MessageGroup, error) {
	row := q.db.QueryRowContext(ctx, createMessageGroup, groupName)
	var i MessageGroup
	err := row.Scan(&i.GroupID, &i.GroupName)
	return i, err
}

const deleteMessageGroup = `-- name: DeleteMessageGroup :exec
DELETE FROM message_group WHERE group_id = $1
`

func (q *Queries) DeleteMessageGroup(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMessageGroup, groupID)
	return err
}
