// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message_group.sql

package db

import (
	"context"
)

const createMessageGroup = `-- name: CreateMessageGroup :one
INSERT INTO message_group (group_name)
VALUES ($1)
RETURNING group_id, group_name
`

func (q *Queries) CreateMessageGroup(ctx context.Context, groupName string) (MessageGroup, error) {
	row := q.db.QueryRowContext(ctx, createMessageGroup, groupName)
	var i MessageGroup
	err := row.Scan(&i.GroupID, &i.GroupName)
	return i, err
}
